# Generated by Django 4.2.5 on 2023-09-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('surname', models.CharField(max_length=255, verbose_name='Cognome')),
                ('tax_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('surname', models.CharField(max_length=255, verbose_name='Cognome')),
                ('tax_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour', models.DateTimeField(verbose_name='Data e ora')),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointments.patient', verbose_name='Dottore')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='appointments.patient', verbose_name='Paziente')),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Appuntamenti',
            },
        ),
    ]
