# Generated by Django 4.2.5 on 2023-09-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Dottore', 'verbose_name_plural': 'Dottori'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paziente', 'verbose_name_plural': 'Pazienti'},
        ),
    ]
