# Generated by Django 4.2.5 on 2023-09-04 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_created_at_appointment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_hour',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 18, 16, 44, 660850), verbose_name='Da'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 18, 16, 50, 814607), verbose_name='A'),
            preserve_default=False,
        ),
    ]
