# Generated by Django 4.2.5 on 2023-09-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_date_hour_appointment_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointments.doctor', verbose_name='Dottore'),
        ),
    ]
